In [53]:
"""
#remettre le all_dataset
from scipy.sparse import csc_matrix
from scipy.spatial.distance import pdist, squareform
from mangaki.utils.svd import MangakiSVD
from mangaki.utils.values import rating_values
from mangaki.models import Rating
import pandas, random
import numpy as np

#source : from 'csv' or 'database' ?

#from csv
"""
#ratings = pandas.read_csv('../data/ratings.csv', header=None).as_matrix()	
#nb_users = ratings[:,0].max()+1
#nb_items = ratings[:,1].max()+1
#items = range(0,nb_items)

"""

#from database
A, B = [], []
for user_id, work_id, choice in Rating.objects.values_list('user_id', 'work_id', 'choice'):
	A.append([user_id, work_id])
	B.append(rating_values[choice])

nb_users = np.asarray(A)[:,0].max()+1
nb_items = np.asarray(A)[:,1].max()+1
items = range(0,nb_items)



#2 fonctions donnant une matrice de départ user*item
"""
#récupérer une matrice users*items avec les 1er nb_ratings de ratings.csv
#-soit SVD ayant pour rang rank	
#-soit matrice creuse ayant pour coeff les ratings (creuse[i][j]=rating de l'utilisateur i pour l'oeuvre j)
"""
def get_matrix_svd(rank, nb_ratings):
	X = ratings[:nb_ratings,0:2]
	Y = [rating_values[rating] for rating in ratings[:nb_ratings,2]]
	svd = MangakiSVD(rank) 
	svd.set_parameters(nb_users,nb_items)
	svd.fit(X,Y)
	return svd.VT



def get_matrix_csc(nb_ratings): 
		row = ratings[:,0]
		col = ratings[:,1]
		data = np.array([rating_values[rating] for rating in ratings[:,2]])
		creux = csc_matrix((data, (row, col)), shape=(nb_users, nb_items))
		creuse = creux.toarray()
		return creuse     


#2 fonctions calculant des matrices de similarité

#prendre en argument une metric car pas très intéressant car déjà tt fait en Python

#option = 'cosine' pr 'jaccard'
def similarity(matrix, option): # matrix: dimension nb_users x dimension nb_works
    return 1 - squareform(pdist(matrix, metric=option))
	
class MangakiUniform(object):
	
	def __init__(self, nb_points):
		self.nb_points = nb_points


	def sample_k(self,matrix_similarity):
		uniform_items = list(range(matrix_similarity.shape[0]))
		random.shuffle(uniform_items)
		return uniform_items[:self.nb_points]
    	
	def __str__(self):
		return 'uniform list, nb_points=%d' % self.nb_points

class MangakiDPP(object):

	def __init__(self, nb_points):
		self.nb_points = nb_points
		

	#n'a pas d'intérêt au final
    #TODO : delete
	#similarity_fn='jaccard' or 'coisine'
	#def fit(self, matrix, all_dataset=False): #obtention de la matrice de similarité
	#	matrix_fit=similarity(matrix, similarity_fn)
	#	return matrix_fit
    
    #thanks to mehdidc on github
      # tirer au hasard des points
    #def sample_k(items, similiarity, k, max_nb_iterations=1000, rng=np.random):
	def sample_k(items, L, k, max_nb_iterations=1000, rng=np.random):
	
	#Sample a list of k items from a DPP defined
	#by the similarity matrix L. The algorithm
	#is iterative and runs for max_nb_iterations.
	#The algorithm used is from
	#(Fast Determinantal Point Process Sampling withw
	#Application to Clustering, Byungkon Kang, NIPS 2013)
	
		initial = rng.choice(range(len(items)), size=k, replace=False)
		X = [False] * len(items)
		for i in initial:
			X[i] = True
		X = np.array(X)
		for i in range(max_nb_iterations):
			u = rng.choice(np.arange(len(items))[X])
			v = rng.choice(np.arange(len(items))[~X])
			Y = X.copy()
			Y[u] = False
			L_Y = L[Y, :]
			L_Y = L_Y[:, Y]
			L_Y_inv = np.linalg.inv(L_Y)

			c_v = L[v:v+1, :]
			c_v = c_v[:, v:v+1]
			b_v = L[Y, :]
			b_v = b_v[:, v:v+1]
			c_u = L[u:u+1, :]
			c_u = c_u[:, u:u+1]
			b_u = L[Y, :]
			b_u = b_u[:, u:u+1]

			p = min(1, c_v - np.dot(np.dot(b_v.T, L_Y_inv), b_v) /
	              (c_u - np.dot(np.dot(b_u.T, L_Y_inv.T), b_u)))
			if rng.uniform() <= p:
				X = Y[:]
				X[v] = True
			return np.array(items)[X]
      
	def __str__(self):
		return 'sample dpp list, nb_points=%d' % self.nb_points
   

# comparer : regarder la distance moyenne entre deux points, mesures de dispersion. Avoir un truc qui permet de faire le fit + lancer quelques milliers de samples et regarder la dispersion moyenne
#ajouter des options : quels para de comparaison utilisés ? Diamètre d'ordre r (1 ou 0 ? ), somme de pdist, déterminant du squareform(pdsit) ?


#(pdist(svd.VT[:,sampled_items].T)).sum()

"""
""""""
#distance_sample = []
#distance_uniform = []
#et ds la boucle : 
#distance_sample.append((pdist(svd.VT[:,sampled_items].T)).sum())
#distance_uniform.append((pdist(svd.VT[:,uniform_items].T)).sum())
#puis comparaison entre les deux listes d'une manière ou d'une autre
""""""
"""
""""""

#det de pdist : np.linalg.det(squareform(pdist(svd.VT[:,uniform_items].T, metric='cosine')))

#diamètre d'ordre r : (ici 1 pr l'instant) 
"""
#n = len(sampled_items)
#coefficient_sample = 2/(n*(n-1))*(pdist(svd.VT[:,sampled_items].T).sum())
"""




def compare(type_get_matrix, nb_points, nb_iterations, nb_ratings):
	results_uniform, results_sample_dpp=[], []
	if type_get_matrix=='svd':

		matrix = get_matrix_svd(10, nb_ratings)
	else :
		matrix = get_matrix_svd(10, nb_ratings)
	uniform = MangakiUniform(nb_points)
	dpp = MangakiDDP(matrix, similarity_fn='cosine')
	similarity = dpp.fit(matrix)
	indicateur = 0
	pb = 0
	while indicateur != nb_iterations:
    
		try:
			sampled_items = dpp.sample_k(items, similarity, nb_points)
        

		except np.linalg.linalg.LinAlgError as err:
			pb = 1
		if pb==0:
			indicateur = indicateur+1
        # cas où tt se passe bien, bloc où l'on exécute la comparaison
			uniform_items = uniform.sample_k(items, similarity, nb_points)
        	
			det_uni=np.linalg.det(squareform(pdist(svd.VT[:,uniform_items].T, metric='cosine')))
			det_dpp=np.linalg.det(squareform(pdist(svd.VT[:,sampled_items].T, metric='cosine')))
        	
			diam_uni = 2/(nb_points*(nb_points-1))*(pdist(svd.VT[:,uniform_items].T).sum())
			diam_dpp = 2/(nb_points*(nb_points-1))*(pdist(svd.VT[:,sampled_items].T).sum())

			results_uniform.append([det_uni, diam_uni]) #à compléter : det et diamètre d'ordre r
			results_sample_dpp.append([det_dpp, diam_dpp]) #à compléter : det et diamètre d'ordre r
		else :
			pb = 0
            
""""

In [8]:
#A
#B
#nb_users
#nb_items


In [8]:
#remettre le all_dataset
from scipy.sparse import csc_matrix
from scipy.spatial.distance import pdist, squareform
from mangaki.utils.svd import MangakiSVD
from mangaki.utils.values import rating_values
from mangaki.models import Rating
import pandas, random
import numpy as np

#source : from 'csv' or 'database' ?

#from csv
"""
ratings = pandas.read_csv('../data/ratings.csv', header=None).as_matrix()	
nb_users = ratings[:,0].max()+1
nb_items = ratings[:,1].max()+1
items = range(0,nb_items)

"""

#from database
X, Y = [], []
for user_id, work_id, choice in Rating.objects.values_list('user_id', 'work_id', 'choice'):
	X.append([user_id, work_id])
	Y.append(rating_values[choice])
X=np.asarray(X)
nb_users = np.asarray(X)[:,0].max()+1
nb_items = np.asarray(X)[:,1].max()+1
items = range(0,nb_items)



#2 fonctions donnant une matrice de départ user*item
"""
récupérer une matrice users*items avec les 1er nb_ratings de ratings.csv
-soit SVD ayant pour rang rank	
-soit matrice creuse ayant pour coeff les ratings (creuse[i][j]=rating de l'utilisateur i pour l'oeuvre j)
"""
def get_matrix_svd(rank, nb_ratings):
	Xpr = X[:nb_ratings,0:2]
	Ypr = Y[:nb_ratings]
	svd = MangakiSVD(rank) 
	svd.set_parameters(nb_users,nb_items)
	svd.fit(Xpr,Ypr)
	return svd.VT



def get_matrix_csc(nb_ratings): 
		row = X[:nb_ratings,0]
		col = X[:nb_ratings,1]
		data = np.array(Y[:nb_ratings])
		creux = csc_matrix((data, (row, col)), shape=(nb_users, nb_items))
		creuse = creux.toarray()
		return creuse     


#2 fonctions calculant des matrices de similarité

#prendre en argument une metric car pas très intéressant car déjà tt fait en Python

#option = 'cosine' pr 'jaccard'
def similarity(matrix, option): # matrix: dimension nb_users x dimension nb_works
    return 1 - squareform(pdist(matrix.T, metric=option))
	
class MangakiUniform(object):
	
	def __init__(self, nb_points):
		self.nb_points = nb_points


	def sample_k(self,matrix_similarity):
		uniform_items = list(range(matrix_similarity.shape[0]))
		random.shuffle(uniform_items)
		return uniform_items[:self.nb_points]
    	
	def __str__(self):
		return 'uniform list, nb_points=%d' % self.nb_points

class MangakiDPP(object):

	def __init__(self, nb_points):
		self.nb_points = nb_points


#n'a pas d'intérêt au final
#TODO : delete
#similarity_fn='jaccard' or 'coisine'
#def fit(self, matrix, all_dataset=False): #obtention de la matrice de similarité
#	matrix_fit=similarity(matrix, similarity_fn)
#	return matrix_fit
    
#thanks to mehdidc on github
# tirer au hasard des points
#def sample_k(items, similiarity, k, max_nb_iterations=1000, rng=np.random):
       #def sample_k(items, similiarity, k, max_nb_iterations=1000, rng=np.random):
	def sample_k(self, items, L, k, max_nb_iterations=1000, rng=np.random):
	
	#Sample a list of k items from a DPP defined
	#by the similarity matrix L. The algorithm
	#is iterative and runs for max_nb_iterations.
	#The algorithm used is from
	#(Fast Determinantal Point Process Sampling withw
	#Application to Clustering, Byungkon Kang, NIPS 2013)
	
		initial = rng.choice(range(len(items)), size=k, replace=False)
		X = [False] * len(items)
		for i in initial:
			X[i] = True
		X = np.array(X)
		for i in range(max_nb_iterations):
			u = rng.choice(np.arange(len(items))[X])
			v = rng.choice(np.arange(len(items))[~X])
			Y = X.copy()
			Y[u] = False
			L_Y = L[Y, :]
			L_Y = L_Y[:, Y]
			L_Y_inv = np.linalg.inv(L_Y)

			c_v = L[v:v+1, :]
			c_v = c_v[:, v:v+1]
			b_v = L[Y, :]
			b_v = b_v[:, v:v+1]
			c_u = L[u:u+1, :]
			c_u = c_u[:, u:u+1]
			b_u = L[Y, :]
			b_u = b_u[:, u:u+1]

			p = min(1, c_v - np.dot(np.dot(b_v.T, L_Y_inv), b_v) /
	              (c_u - np.dot(np.dot(b_u.T, L_Y_inv.T), b_u)))
			if rng.uniform() <= p:
				X = Y[:]
				X[v] = True
			return np.array(items)[X]
      
    
	def __str__(self):
		return 'sample dpp list, nb_points=%d' % self.nb_points
   

# comparer : regarder la distance moyenne entre deux points, mesures de dispersion. Avoir un truc qui permet de faire le fit + lancer quelques milliers de samples et regarder la dispersion moyenne
#ajouter des options : quels para de comparaison utilisés ? Diamètre d'ordre r (1 ou 0 ? ), somme de pdist, déterminant du squareform(pdsit) ?


#(pdist(svd.VT[:,sampled_items].T)).sum()

"""
distance_sample = []
distance_uniform = []
et ds la boucle : 
distance_sample.append((pdist(svd.VT[:,sampled_items].T)).sum())
distance_uniform.append((pdist(svd.VT[:,uniform_items].T)).sum())
puis comparaison entre les deux listes d'une manière ou d'une autre
"""


#det de pdist : np.linalg.det(squareform(pdist(svd.VT[:,uniform_items].T, metric='cosine')))

#diamètre d'ordre r : (ici 1 pr l'instant) 
"""
n = len(sampled_items)
coefficient_sample = 2/(n*(n-1))*(pdist(svd.VT[:,sampled_items].T).sum())
"""




def compare(type_get_matrix, nb_points, nb_iterations, nb_ratings):
	results_uniform, results_sample_dpp=[], []
	if type_get_matrix=='svd':

		matrix = get_matrix_svd(10, nb_ratings)
	else :
		matrix = get_matrix_svd(10, nb_ratings)
	uniform = MangakiUniform(nb_points)
	dpp = MangakiDDP(matrix, similarity_fn='cosine')
	similarity = dpp.fit(matrix)
	indicateur = 0
	pb = 0
	while indicateur != nb_iterations:
    
		try:
			sampled_items = dpp.sample_k(items, similarity, nb_points)
        

		except np.linalg.linalg.LinAlgError as err:
			pb = 1
		if pb==0:
			indicateur = indicateur+1
        # cas où tt se passe bien, bloc où l'on exécute la comparaison
			uniform_items = uniform.sample_k(items, similarity, nb_points)
        	
			det_uni=np.linalg.det(squareform(pdist(svd.VT[:,uniform_items].T, metric='cosine')))
			det_dpp=np.linalg.det(squareform(pdist(svd.VT[:,sampled_items].T, metric='cosine')))
        	
			diam_uni = 2/(nb_points*(nb_points-1))*(pdist(svd.VT[:,uniform_items].T).sum())
			diam_dpp = 2/(nb_points*(nb_points-1))*(pdist(svd.VT[:,sampled_items].T).sum())

			results_uniform.append([det_uni, diam_uni]) #à compléter : det et diamètre d'ordre r
			results_sample_dpp.append([det_dpp, diam_dpp]) #à compléter : det et diamètre d'ordre r
		else :
			pb = 0

In [9]:
X

array([[2087,    1],
       [1994,    2],
       [1994,    3],
       ..., 
       [2026, 1384],
       [2026, 9013],
       [2026, 2257]])

In [4]:
#Y

In [10]:
nb_users

2100

In [11]:
nb_items


14416

In [5]:
matrix=get_matrix_svd(10,len(Y))
matrix

Computing M: (2100 × 14416)
fill and center matrix [305 ms]
Shapes (2100, 10) (10,) (10, 14416)
factor matrix [64196 ms]


array([[ -4.76171693e-16,   1.01020483e-01,   5.93017784e-02, ...,
         -0.00000000e+00,  -9.44467650e-05,  -1.60743802e-04],
       [ -4.68550127e-15,  -1.83381462e-02,  -7.07910668e-03, ...,
         -0.00000000e+00,  -1.13539014e-05,  -2.08125466e-03],
       [  8.86429943e-14,  -9.75645378e-02,  -2.02313541e-03, ...,
          0.00000000e+00,   1.00975773e-04,  -2.50413527e-03],
       ..., 
       [ -9.62286895e-11,   9.94452876e-03,   4.81962899e-02, ...,
          0.00000000e+00,   1.33213309e-04,   1.70693862e-02],
       [ -2.70149909e-12,   4.34641981e-02,  -6.43504981e-02, ...,
         -0.00000000e+00,  -2.40416928e-04,  -2.28896131e-03],
       [  4.08080827e-10,   1.52707993e-02,   1.04863916e-01, ...,
          0.00000000e+00,   3.21102824e-04,  -6.47039993e-03]])

In [6]:
matrix2=get_matrix_csc(len(Y))
get_matrix_csc(len(Y))

array([[ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       ..., 
       [ 0. ,  4. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  2. ,  2. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  4. ,  0.5, ...,  0. ,  0. ,  0. ]])

In [7]:
similarity1=similarity(matrix,'cosine')
similarity1

array([[ 1.        , -0.02918436,  0.17222822, ...,         nan,
         0.38887067, -0.54439638],
       [-0.02918436,  1.        ,  0.55066255, ...,         nan,
        -0.68247239,  0.1732992 ],
       [ 0.17222822,  0.55066255,  1.        , ...,         nan,
        -0.45988957,  0.22734672],
       ..., 
       [        nan,         nan,         nan, ...,  1.        ,
                nan,         nan],
       [ 0.38887067, -0.68247239, -0.45988957, ...,         nan,
         1.        , -0.05510931],
       [-0.54439638,  0.1732992 ,  0.22734672, ...,         nan,
        -0.05510931,  1.        ]])

In [10]:
#nan ...
similarity(matrix2,'cosine')

array([[ 1.        ,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan,  1.        ,         nan, ...,         nan,
                nan,         nan],
       [        nan,         nan,  1.        , ...,         nan,
                nan,         nan],
       ..., 
       [        nan,         nan,         nan, ...,  1.        ,
         0.31942857,  0.48542846],
       [        nan,         nan,         nan, ...,  0.31942857,
         1.        ,  0.31879469],
       [        nan,         nan,         nan, ...,  0.48542846,
         0.31879469,  1.        ]])

In [98]:
similarity(matrix,'jaccard')#pb avec les ratings_values 
#à corriger ............

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [ ]:
#mauvaise idée
#similarity(matrix2,'jaccard')

In [11]:
uniform_test=MangakiUniform(10)
uniform_test.sample_k(similarity1)

[7, 1, 9, 0, 8, 6, 2, 5, 4, 3]

In [12]:
items = range(0,nb_items)
dpp_test=MangakiDPP(10)
dpp_test.sample_k(items,similarity1,10)

/home/voisin/mangaki/venv/lib/python3.4/site-packages/ipykernel/__main__.py:116: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 10 but corresponding boolean dimension is 14416



IndexError: index 4167 is out of bounds for axis 0 with size 10